### ISSUE TITLE
kaggle datasets download not working

### ISSUE THREAD

**Issue by junkoda** [Kaggle/kaggle-api#484]
There seems to be a simple bug for `kaggle datasets download` in version 1.5.15. It worked with 1.5.13, and broken in 1.5.14 and 1.5.15.

```
$ kaggle datasets download -d shashwatraman/contrails-images-ash-color
time data 'Mon, 05 Jun 2023 10:54:39 GMT' does not match format '%a, %d %b %Y %X %Z'
```

The command is given by the `Copy API Command` menu in the right top corner of the data page.

The command works with 1.5.13.

```
$ pip install kaggle==1.5.13
$ kaggle datasets download -d shashwatraman/contrails-images-ash-color
```

Version 1.5.14 had an [addition bug](https://github.com/Kaggle/kaggle-api/issues/481) that does not recognize -d option, but without -d it also has the same time data error.

This does not depend on the data. I tried one more data path and get the same error.

**Comment by Philmod** [comment]
I wasn't able to reproduce the bug

![Screenshot 2023-07-05 at 13 03 31](https://github.com/Kaggle/kaggle-api/assets/818310/d232aff9-1118-4b9c-8491-6b441696ee2f)

What OS are you using?

**Comment by junkoda** [comment]
Thanks for the reply. I have investigated a bit more.

The error occurs at:

```
remote_date = datetime.strptime(response.headers['Last-Modified'],
                                  '%a, %d %b %Y %X %Z')
# with response.headers['Last-Modified'] = 'Mon, 05 Jun 2023 10:54:39 GMT'
```
in `kaggle_api_extended.py`.

The problem is that the code depends on locale or other settings for the datetime. In my environment. '%X' requires AM/PM:

```python
from datetime import datetime
datetime.strptime('10:54:39', '%X') # => Error
datetime.strptime('10:54:39 AM', '%X') # => OK
```

- OS: Ubuntu 18.04.6 LTS
- Python 3.10.10
- System Locale: LANG=en_US.UTF-8

I don't know if AM/PM is specified with en_US; I guess it can be selected separately.

Weekday and month might also fail in other languages.

```
from datetime import datetime
import locale

remote_date = datetime.strptime('04 Jul', '%d %b')  # OK for me

locale.setlocale(locale.LC_ALL, 'it_IT.UTF-8')
remote_date = datetime.strptime('04 Jul', '%d %b')  # Error July is luglio in Italian
```

Since I am not familiar with locales, I'll leave the proper locale-independent solution to the professionals. Thanks.

**Comment by Philmod** [comment]
Internal bug: http://b/291578234

**Comment by Philmod** [comment]
It should be fixed in https://github.com/Kaggle/kaggle-api/releases/tag/1.5.16. Let me know if that works for you now.

**Comment by junkoda** [comment]
Thanks! Yes, datasets download worked with 1.5.16.

**Comment by Karesto** [comment]
Up because this error is now back for me.

**Comment by junkoda** [comment]
Thanks. Nice to see someone else other than me is experiencing this error. I've opened an another issue. 
https://github.com/Kaggle/kaggle-api/issues/523
en_US was fixed but not fixed for other languages (locale)
